"""change_size_values_from_float_to_string

Revision ID: 0700b864b68d
Revises: 141e1303120c
Create Date: 2025-11-22 17:36:35.906143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0700b864b68d'
down_revision: Union[str, Sequence[str], None] = '141e1303120c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'shoe_size_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               comment="Shoe size value (e.g., '7', '7.5', '40')",
               existing_comment='Shoe size numeric value (e.g., 7, 40)',
               existing_nullable=True)
    op.alter_column('user_profiles', 'shirt_size_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               comment="Shirt size value (e.g., 'M', 'XL', '10')",
               existing_comment='Shirt size numeric value',
               existing_nullable=True)
    op.alter_column('user_profiles', 'jacket_size_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               comment="Jacket size value (e.g., 'M', 'XL', '10')",
               existing_comment='Jacket size numeric value',
               existing_nullable=True)
    op.alter_column('user_profiles', 'pants_size_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               comment="Pants size value (e.g., '32', '32x34' for waist x inseam)",
               existing_comment='Pants size numeric value (waist or general size)',
               existing_nullable=True)
    op.alter_column('user_profiles', 'top_size_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               comment="Top size value (e.g., 'M', 'XL', '10')",
               existing_comment='Top size numeric value',
               existing_nullable=True)
    op.alter_column('user_profiles', 'dress_size_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               comment="Dress size value (e.g., 'M', 'XL', '10')",
               existing_comment='Dress size numeric value',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'dress_size_value',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Dress size numeric value',
               existing_comment="Dress size value (e.g., 'M', 'XL', '10')",
               existing_nullable=True)
    op.alter_column('user_profiles', 'top_size_value',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Top size numeric value',
               existing_comment="Top size value (e.g., 'M', 'XL', '10')",
               existing_nullable=True)
    op.alter_column('user_profiles', 'pants_size_value',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Pants size numeric value (waist or general size)',
               existing_comment="Pants size value (e.g., '32', '32x34' for waist x inseam)",
               existing_nullable=True)
    op.alter_column('user_profiles', 'jacket_size_value',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Jacket size numeric value',
               existing_comment="Jacket size value (e.g., 'M', 'XL', '10')",
               existing_nullable=True)
    op.alter_column('user_profiles', 'shirt_size_value',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Shirt size numeric value',
               existing_comment="Shirt size value (e.g., 'M', 'XL', '10')",
               existing_nullable=True)
    op.alter_column('user_profiles', 'shoe_size_value',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Shoe size numeric value (e.g., 7, 40)',
               existing_comment="Shoe size value (e.g., '7', '7.5', '40')",
               existing_nullable=True)
    # ### end Alembic commands ###
