"""add_gender_to_user_profile

Revision ID: 141e1303120c
Revises: 319716abd7ca
Create Date: 2025-11-22 16:55:28.964427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141e1303120c'
down_revision: Union[str, Sequence[str], None] = '319716abd7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = sa.Enum('MALE', 'FEMALE', name='gender_enum')
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user_profiles', sa.Column('gender', gender_enum, nullable=True, comment="User's gender identity"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'gender')
    gender_enum = sa.Enum('MALE', 'FEMALE', name='gender_enum')
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
