"""create_unified_reviews_table

Revision ID: 225847d2b447
Revises: b5262e7f63a6
Create Date: 2025-12-05 10:35:28.235331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225847d2b447'
down_revision: Union[str, Sequence[str], None] = 'b5262e7f63a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False, comment="Type of item being reviewed: 'product' (catalog item) or 'boutique'"),
    sa.Column('item_id', sa.String(length=50), nullable=False, comment='ID of the item being reviewed (catalog_item_id or boutique_id as string)'),
    sa.Column('user_id', sa.String(), nullable=False, comment='User who wrote the review'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Rating value (1-5 stars)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Review comment/text'),
    sa.Column('images', sa.JSON(), nullable=True, comment='Array of image URLs associated with the review'),
    sa.Column('review_metadata', sa.JSON(), nullable=True, comment='Additional review metadata (product/boutique details, image_count, review_length, submitted_at, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when review was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when review was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_item_rating', 'reviews', ['item_type', 'item_id', 'rating'], unique=False)
    op.create_index('ix_reviews_item_type', 'reviews', ['item_type'], unique=False)
    op.create_index('ix_reviews_item_type_id', 'reviews', ['item_type', 'item_id'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_item_type_id', table_name='reviews')
    op.drop_index('ix_reviews_item_type', table_name='reviews')
    op.drop_index('ix_reviews_item_rating', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
