"""add_is_approved_field_to_reviews

Revision ID: 2b08142bb0ce
Revises: 225847d2b447
Create Date: 2025-12-05 10:59:41.441686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b08142bb0ce'
down_revision: Union[str, Sequence[str], None] = '225847d2b447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, then set default for existing rows, then make it NOT NULL
    op.add_column('reviews', sa.Column('is_approved', sa.Boolean(), nullable=True, comment='Whether the review has been approved by an admin (defaults to False for moderation)'))
    # Set default value for existing reviews (False = needs moderation)
    op.execute("UPDATE reviews SET is_approved = FALSE WHERE is_approved IS NULL")
    # Now make it NOT NULL
    op.alter_column('reviews', 'is_approved', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_approved')
    # ### end Alembic commands ###
