"""create_wardrobe_items_table

Revision ID: 319716abd7ca
Revises: da9711883b22
Create Date: 2025-11-21 12:02:57.698173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319716abd7ca'
down_revision: Union[str, Sequence[str], None] = 'da9711883b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wardrobe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Item title/name'),
    sa.Column('category', sa.String(length=50), nullable=False, comment="Item category (e.g., 'shirt', 'pants', 'dress')"),
    sa.Column('colors', sa.JSON(), nullable=False, comment="List of colors (e.g., ['burgundy', 'olive green', 'black'])"),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='URL to item image'),
    sa.Column('tags', sa.JSON(), nullable=True, comment="List of tags for filtering/searching (e.g., ['short sleeve', 'geometric', 'casual', 'summer', 'silk'])"),
    sa.Column('status', sa.Enum('CLEAN', 'WORN', 'DIRTY', name='item_status_enum'), nullable=True, comment='Current item status (clean, worn, dirty)'),
    sa.Column('last_worn_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when item was last worn (nullable for unworn items)'),
    sa.Column('wear_count', sa.Integer(), nullable=False, comment='Number of times item has been worn'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when item was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when item was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wardrobe_items_category', 'wardrobe_items', ['category'], unique=False)
    op.create_index('ix_wardrobe_items_user_category', 'wardrobe_items', ['user_id', 'category'], unique=False)
    op.create_index('ix_wardrobe_items_user_id', 'wardrobe_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wardrobe_items_user_id', table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_user_category', table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_category', table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    # ### end Alembic commands ###
