"""create_boutique_looks_table

Revision ID: 3683265c723a
Revises: e816bc013ed4
Create Date: 2025-12-01 10:49:21.653110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3683265c723a'
down_revision: Union[str, Sequence[str], None] = 'e816bc013ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boutique_looks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False, comment='Boutique owner user ID - links look to boutique'),
    sa.Column('title', sa.String(length=200), nullable=False, comment="Look title/name (e.g., 'Summer Casual Outfit')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the look and styling notes'),
    sa.Column('style', sa.String(length=50), nullable=False, comment="Style identifier (e.g., 'casual', 'formal', 'streetwear', 'bohemian')"),
    sa.Column('product_ids', sa.JSON(), nullable=False, comment="Array of catalog item IDs (2-5 items). Example: ['1', '2', '3']"),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='URL to styled image showing the complete look (can be generated via virtual try-on)'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='Whether this look is featured/promoted (default: False)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when look was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when look was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_boutique_looks_is_featured', 'boutique_looks', ['is_featured'], unique=False)
    op.create_index('ix_boutique_looks_style', 'boutique_looks', ['style'], unique=False)
    op.create_index('ix_boutique_looks_user_featured', 'boutique_looks', ['user_id', 'is_featured'], unique=False)
    op.create_index('ix_boutique_looks_user_id', 'boutique_looks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_boutique_looks_user_id', table_name='boutique_looks')
    op.drop_index('ix_boutique_looks_user_featured', table_name='boutique_looks')
    op.drop_index('ix_boutique_looks_style', table_name='boutique_looks')
    op.drop_index('ix_boutique_looks_is_featured', table_name='boutique_looks')
    op.drop_table('boutique_looks')
    # ### end Alembic commands ###
