"""create boutique_profiles table

Revision ID: 61047fa1cae7
Revises: a4b6b07620d5
Create Date: 2025-11-29 18:46:32.526094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61047fa1cae7'
down_revision: Union[str, Sequence[str], None] = 'a4b6b07620d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boutique_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False, comment='User ID (unique - one profile per user)'),
    sa.Column('business_name', sa.String(length=200), nullable=True, comment='Name of the boutique/business'),
    sa.Column('business_address', sa.String(length=500), nullable=True, comment='Business address (street, city, state, zip, country)'),
    sa.Column('business_category', sa.String(length=100), nullable=True, comment='Category of the boutique/business'),
    sa.Column('business_city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('business_state', sa.String(length=100), nullable=True, comment='State/province'),
    sa.Column('business_zip', sa.String(length=20), nullable=True, comment='ZIP/postal code'),
    sa.Column('business_country', sa.String(length=100), nullable=True, comment='Country'),
    sa.Column('business_phone', sa.String(length=20), nullable=True, comment='Business phone number'),
    sa.Column('business_email', sa.String(length=255), nullable=True, comment='Business email (may differ from user email)'),
    sa.Column('business_website', sa.String(length=500), nullable=True, comment='Business website URL'),
    sa.Column('business_social_media', sa.JSON(), nullable=True, comment="Social media links in JSON format (e.g., {'instagram': '...', 'facebook': '...'})"),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='URL to boutique/business logo image'),
    sa.Column('currency', sa.String(length=3), nullable=True, comment="Currency code (e.g., 'USD', 'EUR', 'GBP')"),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment="Timezone (e.g., 'America/New_York', 'Europe/London')"),
    sa.Column('language', sa.String(length=10), nullable=True, comment="Language code (e.g., 'en', 'fr', 'es')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when profile was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when profile was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_boutique_profiles_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boutique_profiles')
    # ### end Alembic commands ###
