"""create catalog items and reviews tables

Revision ID: a4b6b07620d5
Revises: d5ce3cda529a
Create Date: 2025-11-27 18:56:55.729005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b6b07620d5'
down_revision: Union[str, Sequence[str], None] = 'd5ce3cda529a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Product name'),
    sa.Column('category', sa.String(length=50), nullable=False, comment="Product category (e.g., 'jeans', 'shirt', 'dress')"),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='Brand name (optional for generic/unbranded items)'),
    sa.Column('cost_price', sa.Integer(), nullable=True, comment='Cost price in smallest currency unit (cents/pence). What the store paid for the item. Optional - can be hidden from non-admin users. Example: 30000 = $300.00'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Regular selling price in smallest currency unit (cents/pence). Example: 55000 = $550.00'),
    sa.Column('discount_price', sa.Integer(), nullable=True, comment='Discount/sale price in smallest currency unit (cents/pence). Only set when item is on sale. Example: 45000 = $450.00'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='URL to product image'),
    sa.Column('sales', sa.Integer(), nullable=False, comment='Number of units sold'),
    sa.Column('revenue', sa.Integer(), nullable=False, comment='Total revenue in smallest currency unit (cents/pence)'),
    sa.Column('views', sa.Integer(), nullable=False, comment='Number of times product was viewed'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='Available inventory count'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Product status (active, inactive, out_of_stock, discontinued)'),
    sa.Column('tags', sa.JSON(), nullable=True, comment="List of tags for filtering/searching (e.g., ['denim', 'moto', 'casual'])"),
    sa.Column('colors', sa.JSON(), nullable=True, comment="List of available colors (e.g., ['navy blue', 'white'])"),
    sa.Column('description', sa.Text(), nullable=True, comment='Product description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when item was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when item was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_items_brand', 'catalog_items', ['brand'], unique=False)
    op.create_index('ix_catalog_items_category', 'catalog_items', ['category'], unique=False)
    op.create_index('ix_catalog_items_category_status', 'catalog_items', ['category', 'status'], unique=False)
    op.create_index('ix_catalog_items_status', 'catalog_items', ['status'], unique=False)
    op.create_table('catalog_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False, comment='Catalog item being reviewed'),
    sa.Column('user_id', sa.String(), nullable=False, comment='User who wrote the review'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Rating value (1-5 stars)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Review comment/text'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when review was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when review was last updated'),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_reviews_item_id', 'catalog_reviews', ['catalog_item_id'], unique=False)
    op.create_index('ix_catalog_reviews_item_rating', 'catalog_reviews', ['catalog_item_id', 'rating'], unique=False)
    op.create_index('ix_catalog_reviews_user_id', 'catalog_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_reviews_user_id', table_name='catalog_reviews')
    op.drop_index('ix_catalog_reviews_item_rating', table_name='catalog_reviews')
    op.drop_index('ix_catalog_reviews_item_id', table_name='catalog_reviews')
    op.drop_table('catalog_reviews')
    op.drop_index('ix_catalog_items_status', table_name='catalog_items')
    op.drop_index('ix_catalog_items_category_status', table_name='catalog_items')
    op.drop_index('ix_catalog_items_category', table_name='catalog_items')
    op.drop_index('ix_catalog_items_brand', table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
