"""create_user_profile

Revision ID: c21ab2d8d96c
Revises: d124758b29c5
Create Date: 2025-11-18 22:19:04.897652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21ab2d8d96c'
down_revision: Union[str, Sequence[str], None] = 'd124758b29c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True, comment='Height in centimeters'),
    sa.Column('waist_cm', sa.Float(), nullable=True, comment='Waist measurement in centimeters'),
    sa.Column('measurements', sa.JSON(), nullable=True, comment="Gender-specific body measurements in JSON format. Keys should include units (e.g., 'bust_cm', 'chest_cm')"),
    sa.Column('shoe_size', sa.Enum('SIZE_5', 'SIZE_5_5', 'SIZE_6', 'SIZE_6_5', 'SIZE_7', 'SIZE_7_5', 'SIZE_8', 'SIZE_8_5', 'SIZE_9', 'SIZE_9_5', 'SIZE_10', 'SIZE_10_5', 'SIZE_11', 'SIZE_11_5', 'SIZE_12', 'SIZE_13', 'SIZE_14', name='shoesize'), nullable=True, comment='U.S. shoe size'),
    sa.Column('shirt_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', name='clothingsize'), nullable=True, comment="Men's shirt size (U.S. Standard)"),
    sa.Column('jacket_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', name='clothingsize'), nullable=True, comment="Men's jacket size (U.S. Standard)"),
    sa.Column('pants_size', sa.String(length=20), nullable=True, comment="Men's pants size (e.g., '32x34' for waist x inseam)"),
    sa.Column('top_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', name='clothingsize'), nullable=True, comment="Women's top size (U.S. Standard)"),
    sa.Column('dress_size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', name='clothingsize'), nullable=True, comment="Women's dress size (U.S. Standard)"),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True, comment="URL to user's profile picture"),
    sa.Column('full_body_image_url', sa.String(length=500), nullable=True, comment="URL to user's full body image"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
