"""add_cover_image_url_and_featured_to_boutique_profile

Revision ID: c71bff1c8f26
Revises: 7052a9062782
Create Date: 2025-12-09 19:17:07.800741

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c71bff1c8f26"
down_revision: Union[str, Sequence[str], None] = "7052a9062782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boutique_profiles",
        sa.Column(
            "cover_image_url",
            sa.String(length=500),
            nullable=True,
            comment="URL to boutique cover/hero image (uploaded by boutique owner)",
        ),
    )
    # Add featured column with default value False for existing rows
    op.add_column(
        "boutique_profiles",
        sa.Column(
            "featured",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="Whether the boutique is featured (admin-managed flag)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("boutique_profiles", "featured")
    op.drop_column("boutique_profiles", "cover_image_url")
    # ### end Alembic commands ###
