"""create virtual try on sessions table

Revision ID: d5ce3cda529a
Revises: 31d7bac6547d
Create Date: 2025-11-25 10:50:59.125744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ce3cda529a'
down_revision: Union[str, Sequence[str], None] = '31d7bac6547d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_try_on_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False, comment='WorkOS user ID for the session owner'),
    sa.Column('full_body_image_uri', sa.String(length=500), nullable=False, comment='User-uploaded body image used for the try-on run'),
    sa.Column('generated_image_uri', sa.String(length=500), nullable=False, comment='Resulting image URI from the generation workflow'),
    sa.Column('use_clean_background', sa.Boolean(), nullable=False, comment='Whether the generation used a clean background'),
    sa.Column('custom_instructions', sa.String(length=500), nullable=True, comment='Optional custom instructions provided by the user'),
    sa.Column('selected_items', sa.JSON(), nullable=False, comment='Snapshot of the wardrobe items selected for this session'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_try_on_sessions_user_id'), 'virtual_try_on_sessions', ['user_id'], unique=False)
    op.alter_column('wardrobe_items', 'status',
               existing_type=sa.VARCHAR(length=10),
               comment='Current item status (clean, planned, worn, dirty)',
               existing_comment='Current item status (clean, worn, dirty)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wardrobe_items', 'status',
               existing_type=sa.VARCHAR(length=10),
               comment='Current item status (clean, worn, dirty)',
               existing_comment='Current item status (clean, planned, worn, dirty)',
               existing_nullable=True)
    op.drop_index(op.f('ix_virtual_try_on_sessions_user_id'), table_name='virtual_try_on_sessions')
    op.drop_table('virtual_try_on_sessions')
    # ### end Alembic commands ###
