"""size_value_and_standard_fields

Revision ID: da9711883b22
Revises: c21ab2d8d96c
Create Date: 2025-11-19 10:49:26.699569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da9711883b22'
down_revision: Union[str, Sequence[str], None] = 'c21ab2d8d96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


size_standard_enum = sa.Enum('US', 'UK', 'EU', 'JP', 'AU', 'OTHER', name='size_standard_enum')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    size_standard_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user_profiles', sa.Column('shoe_size_value', sa.Float(), nullable=True, comment='Shoe size numeric value (e.g., 7, 40)'))
    op.add_column('user_profiles', sa.Column('shoe_size_standard', size_standard_enum, nullable=True, comment='Standard for shoe size (e.g., US, EU)'))
    op.add_column('user_profiles', sa.Column('shirt_size_value', sa.Float(), nullable=True, comment='Shirt size numeric value'))
    op.add_column('user_profiles', sa.Column('shirt_size_standard', size_standard_enum, nullable=True, comment='Standard for shirt size (e.g., US, EU)'))
    op.add_column('user_profiles', sa.Column('jacket_size_value', sa.Float(), nullable=True, comment='Jacket size numeric value'))
    op.add_column('user_profiles', sa.Column('jacket_size_standard', size_standard_enum, nullable=True, comment='Standard for jacket size (e.g., US, EU)'))
    op.add_column('user_profiles', sa.Column('pants_size_value', sa.Float(), nullable=True, comment='Pants size numeric value (waist or general size)'))
    op.add_column('user_profiles', sa.Column('pants_size_standard', size_standard_enum, nullable=True, comment='Standard for pants size (e.g., US, EU)'))
    op.add_column('user_profiles', sa.Column('top_size_value', sa.Float(), nullable=True, comment='Top size numeric value'))
    op.add_column('user_profiles', sa.Column('top_size_standard', size_standard_enum, nullable=True, comment='Standard for top size (e.g., US, EU)'))
    op.add_column('user_profiles', sa.Column('dress_size_value', sa.Float(), nullable=True, comment='Dress size numeric value'))
    op.add_column('user_profiles', sa.Column('dress_size_standard', size_standard_enum, nullable=True, comment='Standard for dress size (e.g., US, EU)'))
    op.drop_column('user_profiles', 'shoe_size')
    op.drop_column('user_profiles', 'pants_size')
    op.drop_column('user_profiles', 'dress_size')
    op.drop_column('user_profiles', 'shirt_size')
    op.drop_column('user_profiles', 'jacket_size')
    op.drop_column('user_profiles', 'top_size')
    op.execute("DROP TYPE IF EXISTS shoesize")
    op.execute("DROP TYPE IF EXISTS clothingsize")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    clothingsize = postgresql.ENUM('XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', name='clothingsize')
    clothingsize.create(op.get_bind(), checkfirst=True)
    shoesize = postgresql.ENUM('SIZE_5', 'SIZE_5_5', 'SIZE_6', 'SIZE_6_5', 'SIZE_7', 'SIZE_7_5', 'SIZE_8', 'SIZE_8_5', 'SIZE_9', 'SIZE_9_5', 'SIZE_10', 'SIZE_10_5', 'SIZE_11', 'SIZE_11_5', 'SIZE_12', 'SIZE_13', 'SIZE_14', name='shoesize')
    shoesize.create(op.get_bind(), checkfirst=True)

    op.add_column('user_profiles', sa.Column('top_size', clothingsize, autoincrement=False, nullable=True, comment="Women's top size (U.S. Standard)"))
    op.add_column('user_profiles', sa.Column('jacket_size', clothingsize, autoincrement=False, nullable=True, comment="Men's jacket size (U.S. Standard)"))
    op.add_column('user_profiles', sa.Column('shirt_size', clothingsize, autoincrement=False, nullable=True, comment="Men's shirt size (U.S. Standard)"))
    op.add_column('user_profiles', sa.Column('dress_size', clothingsize, autoincrement=False, nullable=True, comment="Women's dress size (U.S. Standard)"))
    op.add_column('user_profiles', sa.Column('pants_size', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment="Men's pants size (e.g., '32x34' for waist x inseam)"))
    op.add_column('user_profiles', sa.Column('shoe_size', shoesize, autoincrement=False, nullable=True, comment='U.S. shoe size'))
    op.drop_column('user_profiles', 'dress_size_standard')
    op.drop_column('user_profiles', 'dress_size_value')
    op.drop_column('user_profiles', 'top_size_standard')
    op.drop_column('user_profiles', 'top_size_value')
    op.drop_column('user_profiles', 'pants_size_standard')
    op.drop_column('user_profiles', 'pants_size_value')
    op.drop_column('user_profiles', 'jacket_size_standard')
    op.drop_column('user_profiles', 'jacket_size_value')
    op.drop_column('user_profiles', 'shirt_size_standard')
    op.drop_column('user_profiles', 'shirt_size_value')
    op.drop_column('user_profiles', 'shoe_size_standard')
    op.drop_column('user_profiles', 'shoe_size_value')
    size_standard_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
