"""add user_id to catalog_items and coordinates to boutique_profiles

Revision ID: e816bc013ed4
Revises: 61047fa1cae7
Create Date: 2025-11-29 20:46:25.802562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e816bc013ed4'
down_revision: Union[str, Sequence[str], None] = '61047fa1cae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add latitude and longitude to boutique_profiles (nullable)
    op.add_column('boutique_profiles', sa.Column('latitude', sa.Float(), nullable=True, comment='Business latitude in decimal degrees (for proximity search). Example: 40.7128 for New York'))
    op.add_column('boutique_profiles', sa.Column('longitude', sa.Float(), nullable=True, comment='Business longitude in decimal degrees (for proximity search). Example: -74.0060 for New York'))
    
    # Add user_id to catalog_items (handle existing data)
    # Step 1: Add column as nullable first
    op.add_column('catalog_items', sa.Column('user_id', sa.String(), nullable=True, comment='Boutique owner user ID - links catalog item to boutique'))
    
    # Step 2: If there are existing catalog items, they need to be assigned to a boutique owner
    # For now, we'll delete any orphaned items (items without a boutique owner)
    # In production, you might want to assign them to a default boutique or migrate them
    op.execute("DELETE FROM catalog_items WHERE user_id IS NULL")
    
    # Step 3: Now make it non-nullable
    op.alter_column('catalog_items', 'user_id', nullable=False)
    
    # Step 4: Create index and foreign key
    op.create_index('ix_catalog_items_user_id', 'catalog_items', ['user_id'], unique=False)
    op.create_foreign_key('fk_catalog_items_user_id', 'catalog_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_catalog_items_user_id', 'catalog_items', type_='foreignkey')
    op.drop_index('ix_catalog_items_user_id', table_name='catalog_items')
    op.drop_column('catalog_items', 'user_id')
    op.drop_column('boutique_profiles', 'longitude')
    op.drop_column('boutique_profiles', 'latitude')
    # ### end Alembic commands ###
